version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      DB_CONNECTION_STRING: "Host=db;Port=5432;Database=poetryglobal;Username=poetryglobal;Password=poetryglobal"
      JWT_SECRET: "6SecretSecretSecretSecretSecretSecret"
      DOTNET_ENVIRONMENT: "Development"

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d

    environment:
      POSTGRES_USER: poetryglobal
      POSTGRES_PASSWORD: poetryglobal
      POSTGRES_DB: poetryglobal

volumes:
  pgdata: